name: Integracion Continua - Reloj Flask

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 1. Construye la imagen de Docker
    - name: Construir imagen de Docker
      run: |
        docker build -t app-reloj:latest .

    # 2. Convierte la imagen en un archivo .tar para poder descargarla
    - name: Guardar imagen de Docker en archivo TAR
      run: |
        docker save app-reloj:latest > app-reloj.tar

    # 3. Sube el archivo a GitHub Actions para que aparezca el botón de descarga
    - name: Subir imagen como Artefacto descargable
      uses: actions/upload-artifact@v4
      with:
        name: imagen-docker-reloj
        path: app-reloj.tar
        retention-days: 1 # Se borrará automáticamente en 1 día para no llenar tu espacio