name: Publicar Imagen en GitHub Packages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Iniciar sesion en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y subir imagen a GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/victor1997h/app-reloj:latest
            ghcr.io/victor1997h/app-reloj:v2

      - name: Mostrar variables (no secretos sensibles)
        run: |
          echo "probando conexiones SSH"
          echo "host: ${{ secrets.VPS_HOST }}"
          echo "usuario: ${{ secrets.VPS_USER }}"
          echo "puerto: ${{ secrets.VPS_PORT }}"

      - name: Probar SSH en el VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "probando conexión SSH en el VPS"
            touch hello.txt

      # 🔥 CREAR CARPETA SEGURA
      - name: Preparar carpeta en VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            mkdir -p ~/despliegue

      # 📦 COPIAR ARCHIVOS
      - name: Copiar archivos al VPS
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          source: "stack.yml,Makefile"
          target: /home/${{ secrets.VPS_USER }}/despliegue

      # 🚀 DESPLIEGUE FINAL CORREGIDO
      - name: Despliegue de los servicios
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "🚀 Desplegando app-reloj"

            # 🔥 IMPORTANTE: usar carpeta correcta
            cd ~/despliegue || exit 1

            ls -la

            # login GHCR (si usas imágenes privadas)
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # actualizar imagen
            docker pull ghcr.io/victor1997h/app-reloj:latest

            # desplegar stack
            echo "==> Desplegando stack..."
            docker stack deploy -c stack.yml app-reloj

            docker service ls